apps/main/lib/main_web/router.ex
defmodule MainWeb.Router do
  use MainWeb, :router
  use Honeybadger.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :live_root do
    plug :put_root_layout, {MainWeb.LayoutView, "root_live.html"}
  end
  pipeline :not_live do
    plug :put_root_layout, {MainWeb.LayoutView, :root}
  end

  pipeline :auth,
    do: plug MainWeb.Auth.AuthAccessPipeline

  scope "/", MainWeb do
    pipe_through [:browser, :not_live]

    get "/", SessionController, :new
    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/webchat/secret", PageController, :secret
    get "/webchat/:api_key", WebChatController, :index
    resources "/tsi/:api_key", TsiController, except: [:delete, :index, :show]
  end

  scope "/admin", MainWeb do
    pipe_through [:browser, :auth, :live_root]

    live "/conversations/:id" , Live.ConversationsView, only: [:index]
    live "/conversations/:id/:tab" , Live.ConversationsView, only: [:index]
    live "/campaigns" , Live.CampaignsView
    live "/tickets" , Live.TicketsView
    live "/tickets/:id" , Live.TicketsView

  end
  scope "/auth" do
    pipe_through [:browser]

  end
  scope "/admin", MainWeb do
    pipe_through [:browser, :auth, :not_live]

    post "/", AdminController, :index
    get "/", AdminController, :index
    get "/export/campaign-recipients/:campaign_id", CampaignController, :export
    delete "/campaign/:campaign_id", CampaignController, :delete

    delete "/logout/:id", SessionController, :delete

    resources "/teams", TeamController do
      resources "/dispositions", DispositionController
      resources "/members", MemberController
      resources "/team-members", TeamMemberController
      resources "/locations", LocationController do
        get "/edit/:provider", LocationController, :edit
        get "/remove", LocationController, :remove_config
        get "/:provider/callback", LocationController, :callback
        post "/:provider/callback", LocationController, :callback
        resources "/class-schedule", ClassScheduleController, only: [:new, :create]
        live "/conversations" , Live.ConversationsView, only: [:index]
        resources "/conversations", ConversationController, except: [:index] do
          resources "/conversation-messages", ConversationMessageController
          put "/close", ConversationController, :close
          put "/open", ConversationController, :open
        end
        resources "/team-members", LocationTeamMemberController
        resources "/holiday-hours", HolidayHourController
        resources "/normal-hours", NormalHourController
        live "/normal-hours/form" , Live.NormalHourForm, :form
        resources "/child-care-hours", ChildCareHourController
        resources "/wifi-network", WifiNetworkController
        resources "/pricing-plans", PricingPlanController
        resources "/saved-replies", SavedReplyController
        resources "/intent", IntentController
        resources "/automations", AutomationController
      end
    end
    live "/admin/teams/:location_team_id/locations/:location_id/normal-hours/" , Live.NormalHourForm, :index

    resources "/users", UserController, only: [:edit, :update]

    # resources "/messages", MessageController, except: [:delete, :new, :create]
  end
  scope "/admin", MainWeb do
    pipe_through [:api, :not_live]
    get "/facebook/hook", FacebookController, :hook
    post "/facebook/hook", FacebookController, :event
    get "/instagram/hook", InstagramController, :hook
    post "/instagram/hook", InstagramController, :event
  end
  scope "/api", MainWeb do
    pipe_through :api

    post "/locations/:location_id/start_flow/:flow_name", FlowController, :flow

    post "/twilio/conversations", Api.ConversationController, :create_
    post "/twilio/conversations/update", Api.ConversationController, :update
    post "/twilio/conversations/close", Api.ConversationController, :close

    get "/sms/inbound", TwilioController, :inbound
    get "/sms/inbound.json", TwilioJsonController, :inbound
    post "/sms/twilio", TwilioController, :inbound
    put "/remove-avatar", AvatarController, :remove_avatar
    put "/assign-team-member", AssignTeamMemberController, :assign
    put "/update-member", UpdateMemberController, :update

    get "/healthcheck", HealthCheckController, :status
  end
end

apps/main/lib/main/intents/class_schedule.ex
defmodule MainWeb.Intents.ClassSchedule do
  @moduledoc """
  This handles class schedule responses
  """

  alias Main.Integrations.Mindbody

  alias Data.{
    ClassSchedule,
    HolidayHours,
    Location
  }

  @behaviour MainWeb.Intents

  @classes "[date]:\n[classes]"
  @no_classes "There are no classes scheduled for [date_prefix]. Please ask about a different day."
  @days_of_week ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

  @impl MainWeb.Intents
  def build_response(args, location) when is_binary(location),
    do: build_response(args, Location.get_by_phone(location))

  def build_response([datetime: {datetime, _}] = _args, location),
    do: build_response([datetime: datetime], location)

  def build_response([datetime: datetime], %{mindbody_location_id: mb_id} = location) when mb_id not in [nil, ""] do
    <<year::binary-size(4), "-", month::binary-size(2), "-", day::binary-size(2), _rest::binary>> = datetime

    date = "#{year}-#{month}-#{day}"

    classes =
      location
      |> Mindbody.get_classes(date, date)
      |> Stream.map(&format_schedule/1)
      |> Enum.join("\n")

    if classes != "" do
      @classes
      |> String.replace("[date]", "#{month}-#{day}-#{year}")
      |> String.replace("[classes]", classes)

    else
      {term, day_of_week} = get_day_of_week({year, month, day}, location.id)

      String.replace(@no_classes, "[date_prefix]", date_prefix({term, day_of_week}, {year, month, day}, location.timezone))
    end
  end

  def build_response([datetime: datetime], location) do
    <<year::binary-size(4), "-", month::binary-size(2), "-", day::binary-size(2), _rest::binary>> = datetime

    date =
    {year, month, day}
    |> convert_to_integer()
    |> Calendar.Date.from_erl!()

    classes =
      location.id
      |> ClassSchedule.all()
      |> Stream.filter(fn class -> class.date == date end)
      |> Stream.map(&format_schedule/1)
      |> Enum.join("\n")

    if classes != "" do
      @classes
      |> String.replace("[date]", "#{month}-#{day}-#{year}")
      |> String.replace("[classes]", classes)

    else
      {term, day_of_week} = get_day_of_week({year, month, day}, location.id)

      String.replace(@no_classes, "[date_prefix]", date_prefix({term, day_of_week}, {year, month, day}, location.timezone))
    end
  end

  def build_response([], %{mindbody_location_id: mb_id} = location) when mb_id not in [nil, ""] do
    date =
      location.timezone
      |> Calendar.Date.today!()
      |> to_string()

    classes =
      location
      |> Mindbody.get_classes(date, date)
      |> Stream.map(&format_schedule/1)
      |> Enum.join("\n")

    if classes != "" do
      @classes
      |> String.replace("[date]", "#{date.month}-#{date.day}-#{date.year}")
      |> String.replace("[classes]", classes)

    else
      String.replace(@no_classes, "[date_prefix]", "Today")
    end
  end

  def build_response([], location) do
    date =
      location.timezone
      |> Calendar.Date.today!()

    classes =
      location.id
      |> ClassSchedule.all()
      |> Stream.filter(fn class -> class.date == date end)
      |> Stream.map(&format_schedule/1)
      |> Enum.join("\n")

    if classes != "" do
      @classes
      |> String.replace("[date]", "#{date.month}-#{date.day}-#{date.year}")
      |> String.replace("[classes]", classes)

    else
      String.replace(@no_classes, "[date_prefix]", "Today")
    end
  end

  def build_response(_, location),
    do: location.default_message

  def format_schedule(class) do
    {h, m, _} = Time.to_erl(class.start_time)

    min = if m < 10, do: "0#{m}", else: m

    start_time = cond do
      h == 12 ->
        "#{h}:#{min} PM"
      h > 12 ->
        "#{h-12}:#{min} PM"
      true ->
        "#{h}:#{min} AM"
    end

    "#{start_time} #{class.class_type} (#{class.instructor})"
  end

  defp get_day_of_week({_year, _month, _day} = date, location) do
    with [holiday] <- find_holiday(location, date) do
      {:holiday, holiday}
    else
      _ ->
        {:normal, lookup_day_of_week(date)}
    end
  end

  defp date_prefix({:normal, day_of_week}, {year, month, day}, timezone) do
    date = Calendar.Date.today!(timezone)
    today = lookup_day_of_week({date.year, date.month, date.day})

    if today == day_of_week do
      "today"
    else
      "#{month}/#{day}/#{year}"
    end
  end

  defp lookup_day_of_week(day) do
    {year, month, day} = convert_to_integer(day)
    index = Calendar.ISO.day_of_week(year, month, day) |> Kernel.-(1)
    Enum.at(@days_of_week, index)
  end

  defp convert_to_integer({year, month, day}) do
    {check_binary(year), check_binary(month), check_binary(day)}
  end

  defp check_binary(value) when is_binary(value), do: String.to_integer(value)
  defp check_binary(value) when is_integer(value), do: value

  defp find_holiday(location_id, erl_date) do
    location_id
    |> HolidayHours.get_by_location_id()
    |> Enum.filter(fn d ->
      match_date?(d.holiday_date, erl_date)
    end)
  end

  defp match_date?(nil, _), do: false

  defp match_date?(date, erl_date) do
    Date.to_erl(date) == erl_date
  end
end

apps/main/lib/main_web/controllers/class_schedule_controller.ex
defmodule MainWeb.ClassScheduleController do
  use MainWeb.SecuredContoller

  alias Data.{Location, ClassSchedule}

  NimbleCSV.define(ScheduleParser, [])

  def new(conn, %{"location_id" => location_id}) do
    location =
      conn
      |> current_user()
      |> Location.get(location_id)

    render(conn, "new.html",
      location: location,
      upload_info: nil,
      teams: teams(conn))
  end

  def create(conn, %{"location_id" => location_id, "csv" => upload}) do
    location =
      conn
      |> current_user()
      |> Location.get(location_id)

    # Clear out location schedules
    location_id
    |> ClassSchedule.get_by_location_id()
    |> Enum.each(&ClassSchedule.delete/1)

    count = upload.path
    |> File.stream!
    |> ScheduleParser.parse_stream
    |> Stream.map(fn [date, start_time, end_time, name, instructor, category, description] ->
      %{
        "date" => date,
        "start_time" => start_time,
        "end_time" => end_time,
        "class_type" => name,
        "instructor" => instructor,
        "class_category" => category,
        "class_description" => description,
        "location_id" => location.id}
    end)
    |> Stream.map(fn(row) -> ClassSchedule.create(row) end)
    |> Enum.count()

    render(conn, "new.html",
      location: location,
      upload_info: %{count: count},
      teams: teams(conn))
  end
end

apps/main/lib/main_web/views/class_schedule_view.ex
defmodule MainWeb.ClassScheduleView do
  use MainWeb, :view
end

apps/main/lib/main_web/templates/class_schedule/new.html.eex
<% location = @location %>

<header class="page-title-bar">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">
                <a href="<%= team_location_path(@conn, :index, location.team_id) %>"><i class="breadcrumb-icon fa fa-angle-left mr-2"></i>Locations</a>
            </li>
        </ol>
    </nav>
    <h6 class="page-title">Edit <%= location.location_name %></h6>
</header>

<div class="page-section">
    <div class="row">
        <div class="col-lg-4">
            <div class="card card-fluid">
                <div class="card-header">
                    <nav class="nav nav-tabs flex-column border-0">
                        <a href="<%= team_location_path(@conn, :edit, location.team_id, location.id) %>" class="nav-link">Details</a>
                        <a href="<%=team_location_automation_path(@conn, :new, location.team_id, location.id)%>" class="nav-link">Answers</a>
                        <a href="<%= team_location_normal_hour_path(@conn, :index, location.team_id, location.id) %>" class="nav-link">Normal Hours</a>
                        <a href="<%= team_location_holiday_hour_path(@conn, :index, location.team_id, location.id) %>" class="nav-link">Special Hours</a>
                        <a href="<%= team_location_child_care_hour_path(@conn, :index, location.team_id, location.id) %>" class="nav-link">Child Care Hours</a>
                        <a href="<%= team_location_wifi_network_path(@conn, :index, location.team_id, location.id) %>" class="nav-link">Wifi Network</a>
                        <a href="<%= team_location_pricing_plan_path(@conn, :index, location.team_id, location.id) %>" class="nav-link">Pass Prices</a>
                        <a href="<%= team_location_class_schedule_path(@conn, :new, location.team_id, location.id) %>" class="nav-link active">Class Schedule Upload</a>
                        <a href="<%= team_location_saved_reply_path(@conn, :new, location.team_id, location.id) %>" class="nav-link">Saved Replies</a>
                        <a href="<%= team_location_intent_path(@conn, :new, location.team_id, location.id) %>" class="nav-link ">Intents</a>

                    </nav>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card card-fluid">
                <h6 class="card-header"> Class Schedule Uploads</h6><!-- .card-body -->
                <div class="card-body">
                    <%= form_for @conn, team_location_class_schedule_path(@conn, :create, @location.team_id, @location.id), [multipart: true], fn f -> %>
                        <div class="form-group">
                            <%= file_input f, :csv, accept: "text/csv, .csv", class: "form-control" %>
                        </div>
                        <%= submit "Upload" %>
                    <% end %>

                </div><!-- /.card-body -->
                <div>
                    <%= if @upload_info do %>
                        <div class="list-group-item d-flex justify-content-between align-items-center">
                            <div class="alert alert-success mx-3"> The file was successfully uploaded <b><%= @upload_info.count %> new records. </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>